remote_theme: BDHU/minimalist
plugins:
  - jekyll-remote-theme


#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme

title: [Crypto currency User-Friendly Micro payment Channels]
description: [by <br> Medha Upadhyay <br> Isa Vidanes <br> Minh Luc <br> Priscilla Hui <br> with mentor Sheffield Nolan <br>] 

sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/medhaupadhyay/Micropayment-Channel/tree/main
   - name: Report
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><g fill="none" stroke="currentColor" stroke-linejoin="round" stroke-width="2"><path stroke-linecap="round" d="M4 4v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8.342a2 2 0 0 0-.602-1.43l-4.44-4.342A2 2 0 0 0 13.56 2H6a2 2 0 0 0-2 2Zm5 9h6m-6 4h3"/><path d="M14 2v4a2 2 0 0 0 2 2h4"/></g></svg>
    link: https://github.com/medhaupadhyay/Micropayment-Channel-Public-Website/blob/8bc6c5cd25eba3b7b0f64bbb77f454c8439c375d/DSC_Capstone_Micropayment_Channel_Report.pdf
  

