remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Cryptocurrency User-Friendly Micropayment Channels]
description: [by <br> Medha Upadhyay <br> Isa Vidanes <br> Minh Luc <br> Priscilla Hui <br> with mentor Sheffield Nolan <br>] 


