remote_theme: BDHU/minimalist
plugins:
  - jekyll-remote-theme


#remote_theme: pages-themes/minimal@v0.2.0
#plugins:
#- jekyll-remote-theme

title: [Crypto currency User-Friendly Micro payment Channels]
description: [by <br> Medha Upadhyay <br> Isa Vidanes <br> Minh Luc <br> Priscilla Hui <br> with mentor Sheffield Nolan <br>] 

sidebar:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/medhaupadhyay/Micropayment-Channel/tree/main
  - name: Report
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24"><path d="M5.242 13.769L0 9.5L12 0l12 9.5l-5.242 4.269C17.548 11.249 14.978 9.5 12 9.5c-2.977 0-5.548 1.748-6.758 4.269zM12 10a7 7 0 1 0 0 14a7 7 0 0 0 0-14z" fill="currentColor"/></svg>
    link: https://github.com/medhaupadhyay/Micropayment-Channel-Public-Website/blob/8bc6c5cd25eba3b7b0f64bbb77f454c8439c375d/DSC_Capstone_Micropayment_Channel_Report.pdf

    #poster (https://github.com/medhaupadhyay/Micropayment-Channel-Public-Website/blob/c1ca19ed867f6983aa0c5404c05f92c06eae8484/DSC%20Capstone%20Micropayment%20Channel%20Poster.pdf)!
  

