remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Cryptocurrency User-Friendly Micropayment Channels]
description: [by Medha Upadhyay\n Isa Vidanes\n Minh Luc \n and Priscilla Hui \n with mentor Sheffield Nolan] 


