remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: [Cryptocurrency: User-Friendly Micropayment Channels]
description: [by Medha Upadhyay, Isa Vidanes, Minh Luc, and Priscilla Hui with mentor Sheffield Nolan] 


